env:
  GITHUB_TOKEN: ENCRYPTED[18b4ba0db4d2030f2229d02b066c5d077a1d642be75c865e63d10cadfc50440d5ddef3bf3d0cab69c4d5f9a4ea77cea4]

macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  name: build and release
  check_clang_script:
    - clang --version
  build_release_script:
    - /usr/bin/env bash ./release-macos-arm64.sh